server:
  port: 9999
spring:
  cloud:
    gateway:
      routes:
      - id: UserService
        uri: lb://UserService
        predicates:
        - Path=/user/**
      - id: HotelService
        uri: lb://HotelService
        predicates:
        - Path=/hotel/**  
      - id: RatingService
        uri: lb://RatingService
        predicates:
        - Path=/ratings/**     

  application:
    name: API-Gateway
